//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ArticlesManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ArticlesManagementService.ArticleManagementService1")]
    public interface ArticleManagementService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/CreateArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/CreateArticleResponse")]
        bool CreateArticle(string title, string author, string content, string tags, string imageLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/CreateArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/CreateArticleResponse")]
        System.Threading.Tasks.Task<bool> CreateArticleAsync(string title, string author, string content, string tags, string imageLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/UpdateArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/UpdateArticleResponse")]
        bool UpdateArticle(int id, string title, string author, string content, string tags, string imageLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/UpdateArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/UpdateArticleResponse")]
        System.Threading.Tasks.Task<bool> UpdateArticleAsync(int id, string title, string author, string content, string tags, string imageLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/DeleteArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/DeleteArticleResponse")]
        bool DeleteArticle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/DeleteArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/DeleteArticleResponse")]
        System.Threading.Tasks.Task<bool> DeleteArticleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/GetArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/GetArticleResponse")]
        ArticleManagementService.Article GetArticle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/GetArticle", ReplyAction="http://tempuri.org/ArticleManagementService1/GetArticleResponse")]
        System.Threading.Tasks.Task<ArticleManagementService.Article> GetArticleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/GetAllArticles", ReplyAction="http://tempuri.org/ArticleManagementService1/GetAllArticlesResponse")]
        ArticleManagementService.Article[] GetAllArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArticleManagementService1/GetAllArticles", ReplyAction="http://tempuri.org/ArticleManagementService1/GetAllArticlesResponse")]
        System.Threading.Tasks.Task<ArticleManagementService.Article[]> GetAllArticlesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArticleManagementService1Channel : WebApplication1.ArticlesManagementService.ArticleManagementService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticleManagementService1Client : System.ServiceModel.ClientBase<WebApplication1.ArticlesManagementService.ArticleManagementService1>, WebApplication1.ArticlesManagementService.ArticleManagementService1 {
        
        public ArticleManagementService1Client() {
        }
        
        public ArticleManagementService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticleManagementService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleManagementService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleManagementService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateArticle(string title, string author, string content, string tags, string imageLink) {
            return base.Channel.CreateArticle(title, author, content, tags, imageLink);
        }
        
        public System.Threading.Tasks.Task<bool> CreateArticleAsync(string title, string author, string content, string tags, string imageLink) {
            return base.Channel.CreateArticleAsync(title, author, content, tags, imageLink);
        }
        
        public bool UpdateArticle(int id, string title, string author, string content, string tags, string imageLink) {
            return base.Channel.UpdateArticle(id, title, author, content, tags, imageLink);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateArticleAsync(int id, string title, string author, string content, string tags, string imageLink) {
            return base.Channel.UpdateArticleAsync(id, title, author, content, tags, imageLink);
        }
        
        public bool DeleteArticle(int id) {
            return base.Channel.DeleteArticle(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteArticleAsync(int id) {
            return base.Channel.DeleteArticleAsync(id);
        }
        
        public ArticleManagementService.Article GetArticle(int id) {
            return base.Channel.GetArticle(id);
        }
        
        public System.Threading.Tasks.Task<ArticleManagementService.Article> GetArticleAsync(int id) {
            return base.Channel.GetArticleAsync(id);
        }
        
        public ArticleManagementService.Article[] GetAllArticles() {
            return base.Channel.GetAllArticles();
        }
        
        public System.Threading.Tasks.Task<ArticleManagementService.Article[]> GetAllArticlesAsync() {
            return base.Channel.GetAllArticlesAsync();
        }
    }
}
